var works = {
	'0': {
		'id': 1,
		'preview': 'http://www.forumdaily.com/wp-content/uploads/2014/07/img-5-0011-600x360.jpg',
		'after_img': 'https://raw.githubusercontent.com/nekita6/eshkereee/master/ilia/img/1.jpg',
		'before_img': 'https://raw.githubusercontent.com/nekita6/eshkereee/master/ilia/img/2.jpg',
		'retoucher': 'Ilya Ignatchenko',
		'photographer': 'Sam Johnson',
		'model': 'Teylor Swift',
		'mua': 'Diana Podolskaya',
		'category': 'high-end'
	},
	'1': {
		'id': 2,
		'preview': 'http://www.forumdaily.com/wp-content/uploads/2014/07/img-5-0011-600x360.jpg',
		'after_img': 'https://raw.githubusercontent.com/nekita6/eshkereee/master/ilia/img/1.jpg',
		'before_img': 'https://raw.githubusercontent.com/nekita6/eshkereee/master/ilia/img/2.jpg',
		'retoucher': 'Ilya Ignatchenko',
		'photographer': 'Sam Johnson',
		'model': 'Teylor Swift',
		'mua': 'Diana Podolskaya',
		'category': 'high-end'
	},
	'2': {
		'id': 3,
		'preview': 'http://www.forumdaily.com/wp-content/uploads/2014/07/img-5-0011-600x360.jpg',
		'after_img': 'https://raw.githubusercontent.com/nekita6/eshkereee/master/ilia/img/1.jpg',
		'before_img': 'https://raw.githubusercontent.com/nekita6/eshkereee/master/ilia/img/2.jpg',
		'retoucher': 'Ilya Ignatchenko',
		'photographer': 'Sam Johnson',
		'model': 'Teylor Swift',
		'mua': 'Diana Podolskaya',
		'category': 'high-end'
	},
	'3': {
		'id': 4,
		'preview': 'http://www.forumdaily.com/wp-content/uploads/2014/07/img-5-0011-600x360.jpg',
		'after_img': 'https://raw.githubusercontent.com/nekita6/eshkereee/master/ilia/img/1.jpg',
		'before_img': 'https://raw.githubusercontent.com/nekita6/eshkereee/master/ilia/img/2.jpg',
		'retoucher': 'Ilya Ignatchenko',
		'photographer': 'Sam Johnson',
		'model': 'Teylor Swift',
		'mua': 'Diana Podolskaya',
		'category': 'high-end'
	},
	'4': {
		'id': 5,
		'preview': 'http://www.forumdaily.com/wp-content/uploads/2014/07/img-5-0011-600x360.jpg',
		'after_img': 'https://raw.githubusercontent.com/nekita6/eshkereee/master/ilia/img/1.jpg',
		'before_img': 'https://raw.githubusercontent.com/nekita6/eshkereee/master/ilia/img/2.jpg',
		'retoucher': 'Ilya Ignatchenko',
		'photographer': 'Sam Johnson',
		'model': 'Teylor Swift',
		'mua': 'Diana Podolskaya',
		'category': 'background replacement'
	},
	'5': {
		'id': 6,
		'preview': 'http://www.forumdaily.com/wp-content/uploads/2014/07/img-5-0011-600x360.jpg',
		'after_img': 'https://raw.githubusercontent.com/nekita6/eshkereee/master/ilia/img/1.jpg',
		'before_img': 'https://raw.githubusercontent.com/nekita6/eshkereee/master/ilia/img/2.jpg',
		'retoucher': 'Ilya Ignatchenko',
		'photographer': 'Sam Johnson',
		'model': 'Teylor Swift',
		'mua': 'Diana Podolskaya',
		'category': 'clipping-path'
	},
	'6': {
		'id': 7,
		'preview': 'http://www.forumdaily.com/wp-content/uploads/2014/07/img-5-0011-600x360.jpg',
		'after_img': 'https://raw.githubusercontent.com/nekita6/eshkereee/master/ilia/img/1.jpg',
		'before_img': 'https://raw.githubusercontent.com/nekita6/eshkereee/master/ilia/img/2.jpg',
		'retoucher': 'Ilya Ignatchenko',
		'photographer': 'Sam Johnson',
		'model': 'Teylor Swift',
		'mua': 'Diana Podolskaya',
		'category': 'restoration'
	},
	'7': {
		'id': 8,
		'preview': 'http://www.forumdaily.com/wp-content/uploads/2014/07/img-5-0011-600x360.jpg',
		'after_img': 'https://raw.githubusercontent.com/nekita6/eshkereee/master/ilia/img/1.jpg',
		'before_img': 'https://raw.githubusercontent.com/nekita6/eshkereee/master/ilia/img/2.jpg',
		'retoucher': 'Ilya Ignatchenko',
		'photographer': 'Sam Johnson',
		'model': 'Teylor Swift',
		'mua': 'Diana Podolskaya',
		'category': 'basic'
	},
	'8': {
		'id': 9,
		'preview': 'http://www.cartoonbucket.com/wp-content/uploads/2015/05/Image-Of-Scooby-Doo-In-Naughty-Mood-600x360.jpg',
		'after_img': 'https://raw.githubusercontent.com/nekita6/eshkereee/master/ilia/img/2.jpg',
		'before_img': 'https://raw.githubusercontent.com/nekita6/eshkereee/master/ilia/img/1.jpg',
		'retoucher': 'Ilya Ignatchenko',
		'photographer': 'Sam Johnson',
		'model': 'Teylor Swift',
		'mua': 'Diana Podolskaya',
		'category': 'advanced'
	},
	'9': {
		'id': 10,
		'preview': 'https://s.aolcdn.com/dims-shared/dims3/GLOB/crop/4288x2602+0+87/resize/600x360!/format/jpg/quality/85/https://s.aolcdn.com/hss/storage/midas/9360517d22e92cd8fffc5750004dab61/200088175/C4KDJY.jpg',
		'after_img': 'https://raw.githubusercontent.com/nekita6/eshkereee/master/ilia/img/1.jpg',
		'before_img': 'https://raw.githubusercontent.com/nekita6/eshkereee/master/ilia/img/2.jpg',
		'retoucher': 'Ilya Ignatchenko',
		'photographer': 'Sam Johnson',
		'model': 'Teylor Swift',
		'mua': 'Diana Podolskaya',
		'category': 'high-end'
	},
	'10': {
		'id': 11,
		'preview': 'http://www.forumdaily.com/wp-content/uploads/2014/07/img-5-0011-600x360.jpg',
		'after_img': 'https://raw.githubusercontent.com/nekita6/eshkereee/master/ilia/img/1.jpg',
		'before_img': 'https://raw.githubusercontent.com/nekita6/eshkereee/master/ilia/img/2.jpg',
		'retoucher': 'Ilya Ignatchenko',
		'photographer': 'Sam Johnson',
		'model': 'Teylor Swift',
		'mua': 'Diana Podolskaya',
		'category': 'background replacement'
	},
	'11': {
		'id': 12,
		'preview': 'http://www.forumdaily.com/wp-content/uploads/2014/07/img-5-0011-600x360.jpg',
		'after_img': 'https://raw.githubusercontent.com/nekita6/eshkereee/master/ilia/img/1.jpg',
		'before_img': 'https://raw.githubusercontent.com/nekita6/eshkereee/master/ilia/img/2.jpg',
		'retoucher': 'Ilya Ignatchenko',
		'photographer': 'Sam Johnson',
		'model': 'Teylor Swift',
		'mua': 'Diana Podolskaya',
		'category': 'clipping-path'
	},
	'12': {
		'id': 13,
		'preview': 'http://www.forumdaily.com/wp-content/uploads/2014/07/img-5-0011-600x360.jpg',
		'after_img': 'https://raw.githubusercontent.com/nekita6/eshkereee/master/ilia/img/1.jpg',
		'before_img': 'https://raw.githubusercontent.com/nekita6/eshkereee/master/ilia/img/2.jpg',
		'retoucher': 'Ilya Ignatchenko',
		'photographer': 'Sam Johnson',
		'model': 'Teylor Swift',
		'mua': 'Diana Podolskaya',
		'category': 'restoration'
	},
	'13': {
		'id': 14,
		'preview': 'http://www.forumdaily.com/wp-content/uploads/2014/07/img-5-0011-600x360.jpg',
		'after_img': 'https://raw.githubusercontent.com/nekita6/eshkereee/master/ilia/img/1.jpg',
		'before_img': 'https://raw.githubusercontent.com/nekita6/eshkereee/master/ilia/img/2.jpg',
		'retoucher': 'Ilya Ignatchenko',
		'photographer': 'Sam Johnson',
		'model': 'Teylor Swift',
		'mua': 'Diana Podolskaya',
		'category': 'basic'
	},
	'14': {
		'id': 15,
		'preview': 'http://www.cartoonbucket.com/wp-content/uploads/2015/05/Image-Of-Scooby-Doo-In-Naughty-Mood-600x360.jpg',
		'after_img': 'https://raw.githubusercontent.com/nekita6/eshkereee/master/ilia/img/2.jpg',
		'before_img': 'https://raw.githubusercontent.com/nekita6/eshkereee/master/ilia/img/1.jpg',
		'retoucher': 'Ilya Ignatchenko',
		'photographer': 'Sam Johnson',
		'model': 'Teylor Swift',
		'mua': 'Diana Podolskaya',
		'category': 'advanced'
	},
	'15': {
		'id': 16,
		'preview': 'https://s.aolcdn.com/dims-shared/dims3/GLOB/crop/4288x2602+0+87/resize/600x360!/format/jpg/quality/85/https://s.aolcdn.com/hss/storage/midas/9360517d22e92cd8fffc5750004dab61/200088175/C4KDJY.jpg',
		'after_img': 'https://raw.githubusercontent.com/nekita6/eshkereee/master/ilia/img/1.jpg',
		'before_img': 'https://raw.githubusercontent.com/nekita6/eshkereee/master/ilia/img/2.jpg',
		'retoucher': 'Ilya Ignatchenko',
		'photographer': 'Sam Johnson',
		'model': 'Teylor Swift',
		'mua': 'Diana Podolskaya',
		'category': 'high-end'
	},
	'16': {
		'id': 17,
		'preview': 'http://www.forumdaily.com/wp-content/uploads/2014/07/img-5-0011-600x360.jpg',
		'after_img': 'https://raw.githubusercontent.com/nekita6/eshkereee/master/ilia/img/1.jpg',
		'before_img': 'https://raw.githubusercontent.com/nekita6/eshkereee/master/ilia/img/2.jpg',
		'retoucher': 'Ilya Ignatchenko',
		'photographer': 'Sam Johnson',
		'model': 'Teylor Swift',
		'mua': 'Diana Podolskaya',
		'category': 'background replacement'
	},
	'17': {
		'id': 18,
		'preview': 'http://www.forumdaily.com/wp-content/uploads/2014/07/img-5-0011-600x360.jpg',
		'after_img': 'https://raw.githubusercontent.com/nekita6/eshkereee/master/ilia/img/1.jpg',
		'before_img': 'https://raw.githubusercontent.com/nekita6/eshkereee/master/ilia/img/2.jpg',
		'retoucher': 'Ilya Ignatchenko',
		'photographer': 'Sam Johnson',
		'model': 'Teylor Swift',
		'mua': 'Diana Podolskaya',
		'category': 'clipping-path'
	},
	'18': {
		'id': 19,
		'preview': 'http://www.forumdaily.com/wp-content/uploads/2014/07/img-5-0011-600x360.jpg',
		'after_img': 'https://raw.githubusercontent.com/nekita6/eshkereee/master/ilia/img/1.jpg',
		'before_img': 'https://raw.githubusercontent.com/nekita6/eshkereee/master/ilia/img/2.jpg',
		'retoucher': 'Ilya Ignatchenko',
		'photographer': 'Sam Johnson',
		'model': 'Teylor Swift',
		'mua': 'Diana Podolskaya',
		'category': 'restoration'
	},
	'19': {
		'id': 20,
		'preview': 'http://www.forumdaily.com/wp-content/uploads/2014/07/img-5-0011-600x360.jpg',
		'after_img': 'https://raw.githubusercontent.com/nekita6/eshkereee/master/ilia/img/1.jpg',
		'before_img': 'https://raw.githubusercontent.com/nekita6/eshkereee/master/ilia/img/2.jpg',
		'retoucher': 'Ilya Ignatchenko',
		'photographer': 'Sam Johnson',
		'model': 'Teylor Swift',
		'mua': 'Diana Podolskaya',
		'category': 'basic'
	},
	'20': {
		'id': 21,
		'preview': 'http://www.cartoonbucket.com/wp-content/uploads/2015/05/Image-Of-Scooby-Doo-In-Naughty-Mood-600x360.jpg',
		'after_img': 'https://raw.githubusercontent.com/nekita6/eshkereee/master/ilia/img/2.jpg',
		'before_img': 'https://raw.githubusercontent.com/nekita6/eshkereee/master/ilia/img/1.jpg',
		'retoucher': 'Ilya Ignatchenko',
		'photographer': 'Sam Johnson',
		'model': 'Teylor Swift',
		'mua': 'Diana Podolskaya',
		'category': 'advanced'
	},
	'21': {
		'id': 22,
		'preview': 'https://s.aolcdn.com/dims-shared/dims3/GLOB/crop/4288x2602+0+87/resize/600x360!/format/jpg/quality/85/https://s.aolcdn.com/hss/storage/midas/9360517d22e92cd8fffc5750004dab61/200088175/C4KDJY.jpg',
		'after_img': 'https://raw.githubusercontent.com/nekita6/eshkereee/master/ilia/img/1.jpg',
		'before_img': 'https://raw.githubusercontent.com/nekita6/eshkereee/master/ilia/img/2.jpg',
		'retoucher': 'Ilya Ignatchenko',
		'photographer': 'Sam Johnson',
		'model': 'Teylor Swift',
		'mua': 'Diana Podolskaya',
		'category': 'high-end'
	}
}